name: Sync Upstream

on:
  schedule:
    # 每天凌晨 0 点（UTC 时间）运行，您也可以根据需要调整
    # 例如：'0 8 * * *' 表示每天早上 8 点（UTC时间）运行
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write # 必须有写入权限才能推送变更

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          # 获取主分支（或其他您希望同步的分支）
          ref: main 
          # token 用于推送，GitHub 自动提供
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Add upstream remote
        run: git remote add upstream https://github.com/LunaTechLab/MoonTV.git # 替换为原仓库的URL

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream into main
        run: git merge --no-edit upstream/main # 合并上游 main 分支到您的 main 分支

      - name: Push changes
        run: git push origin main
